apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask
spec:
  selector:
    app: flask
  ports:
    - name: web
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: LoadBalancer