apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  labels:
    app: react
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react-app
        image: abdelhak245/react-app:0.0.1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
